### ISSUE TITLE
How to change the overall color variation? 

### ISSUE THREAD

**Issue by nmsdvid** [launch-ui/launch-ui#1]
On the homepage https://www.launchuicomponents.com/ there is a way to preview different color variations. How can I change it in my code? It seems the default color is orange.

**Comment by mikolajdobrucki** [comment]
The brand colors are controlled by 2 CSS custom properties:

* `--brand`
* `--brand-foreground`

following a similar naming pattern to shadcn/ui's color variables.

You can find them in `globals.css` and customize them there or override elsewhere if needed. Both variables hold different values for `:root` and `.dark` to support light and dark mode.

I'm planning to add a documentation page dedicated to customization. Once published, I'll it in this thread.

**Comment by mikolajdobrucki** [comment]
Docs for customization are now available: https://www.launchuicomponents.com/docs/getting-started/customization

**Comment by theadepti** [comment]
Is there a way to get the exact colors for one of those pre-built themes?
